<?php
$studio_post_terms = [
	'uehara-1f' => [
		'group' => 'pastis-uehara',
		'taste' => ['natural'],
		'scene' => ['garden','living-dining','kitchen','building'],
		'area' => 'shibuya',
		'price' => '0-to-18000',
	],
	'uehara-2f' => [
		'group' => 'pastis-uehara',
		'taste' => ['natural'],
		'scene' => ['living-dining','bath','washroom','bedroom','terrace','building'],
		'area' => 'shibuya',
		'price' => '18000-to-21000',
	],
	'hiroo-1f' => [
		'group' => 'hiroo-house',
		'taste' => ['natural'],
		'scene' => ['garden','living-dining','kitchen','toilet','entrance','stairs','building'],
		'area' => 'shibuya',
		'price' => '24000-over',
	],
	'hiroo-2f' => [
		'group' => 'hiroo-house',
		'taste' => ['natural'],
		'scene' => ['living-dining','kitchen','bath','toilet','washroom','bedroom','terrace'],
		'area' => 'shibuya',
		'price' => '18000-to-21000',
	],
	'natural' => [
		'group' => 'mimoza-house',
		'taste' => ['natural','antique'],
		'scene' => ['garden','living-dining','kitchen','bath','washroom','bedroom','terrace'],
		'area' => 'shibuya',
		'price' => '21000-to-24000',
	],
	'country' => [
		'group' => 'mimoza-house',
		'taste' => ['antique'],
		'scene' => ['garden','living-dining','kitchen','bedroom','terrace','entrance','building'],
		'area' => 'shibuya',
		'price' => '0-to-18000',
	],
	'shabby-chic' => [
		'group' => 'mimoza-house',
		'taste' => ['european','antique'],
		'scene' => ['garden','living-dining','kitchen','terrace','entrance','building'],
		'area' => 'shibuya',
		'price' => '18000-to-21000',
	],
	'resort' => [
		'group' => 'mimoza-house',
		'taste' => ['antique'],
		'scene' => ['garden','living-dining','kitchen','bath','bedroom','terrace','entrance'],
		'area' => 'shibuya',
		'price' => '18000-to-21000',
	],
	'paruru' => [
		'group' => 'mimoza-house',
		'taste' => ['european'],
		'scene' => ['garden','living-dining','kitchen','washroom','bedroom','entrance','building'],
		'area' => 'shibuya',
		'price' => '21000-to-24000',
	],
	'a-studio' => [
		'group' => 'pastis-sasaduka',
		'taste' => ['modern','european'],
		'scene' => ['garden','terrace','entrance','building','living-dining','kitchen','carpet'],
		'area' => 'setagaya',
		'price' => '24000-over',
	],
	'b-studio' => [
		'group' => 'pastis-sasaduka',
		'taste' => ['modern'],
		'scene' => ['garden','living-dining','kitchen','terrace','entrance','stairs','building'],
		'area' => 'nerima',
		'price' => '24000-over',
	],
	'c-studio' => [
		'group' => 'pastis-sasaduka',
		'taste' => ['natural'],
		'scene' => ['garden','living-dining','kitchen','bath','washroom','bedroom','entrance'],
		'area' => 'kita',
		'price' => '24000-over',
	],
	'basil' => [
		'group' => 'studio-basil',
		'taste' => ['modern','european'],
		'scene' => ['garden','living-dining','bath','washroom','bedroom','terrace','stairs'],
		'area' => 'kita',
		'price' => '24000-over',
	],
	'mint' => [
		'group' => 'studio-basil',
		'taste' => ['natural','modern'],
		'scene' => ['garden','living-dining','kitchen','bedroom','terrace','entrance'],
		'area' => 'kita',
		'price' => '24000-over',
	],
	'maison-de-bran' => [
		'group' => 'maison-de-bran',
		'taste' => ['natural', 'antique'],
		'scene' => ['garden',	'living-dining',	'kitchen',	'washroom',	'bedroom',	'entrance',	'stairs',	'building'],
		'area' => 'shinjuku',
		'price' => '0-to-18000',
	],
	'sage' => [
		'group' => 'studio-basil',
		'taste' => [' '],
		'scene' => [' '],
		'area' => ' ',
		'price' => '　',
	],
	'anchor' => [
		'group' => 'studio-canal',
		'taste' => ['antique'],
		'scene' => ['garden','living-dining','bath','bedroom'],
		'area' => 'koto',
		'price' => '24000-over',
	],
	'compass' => [
		'group' => 'studio-canal',
		'taste' => [' '],
		'scene' => ['bedroom'],
		'area' => 'koto',
		'price' => '24000-over',
	],
	'sailor' => [
		'group' => 'studio-canal',
		'taste' => ['modern','european'],
		'scene' => ['living-dining','kitchen','washroom','bedroom','stairs'],
		'area' => 'koto',
		'price' => '24000-over',
	],
	'lemon' => [
		'group' => 'studio-lemon-lime',
		'taste' => ['natural'],
		'scene' => ['living-dining','kitchen','bedroom','terrace','entrance','building'],
		'area' => 'shinjuku',
		'price' => '0-to-18000',
	],
	'lime' => [
		'group' => 'studio-lemon-lime',
		'taste' => ['european','antique'],
		'scene' => ['living-dining','bedroom'],
		'area' => 'shibuya',
		'price' => '21000-to-24000',
	],
	'flat' => [
		'group' => 'studio-lemon-lime',
		'taste' => ['natural','european'],
		'scene' => ['living-dining','bath','washroom'],
		'area' => 'shibuya',
		'price' => '0-to-18000',
	],
	'1-studio' => [
		'group' => 'studio-couleure',
		'taste' => ['european','antique'],
		'scene' => ['living-dining','stairs'],
		'area' => 'shibuya',
		'price' => '18000-to-21000',
	],
	'2-studio' => [
		'group' => 'studio-couleure',
		'taste' => ['natural'],
		'scene' => ['garden','living-dining','kitchen','toilet','bedroom','terrace','stairs'],
		'area' => 'shibuya',
		'price' => '24000-over',
	],
	'3-studio' => [
		'group' => 'studio-couleure',
		'taste' => ['natural','modern','european'],
		'scene' => ['garden','living-dining','bath','washroom','bedroom','terrace','stairs'],
		'area' => 'shibuya',
		'price' => '24000-over',
	],
	'4-studio' => [
		'group' => 'studio-couleure',
		'taste' => ['natural'],
		'scene' => ['garden','living-dining','kitchen','bath','toilet','washroom','bedroom'],
		'area' => 'shibuya',
		'price' => '24000-over',
	],
	'atlier-todoroki' => [
		'group' => 'management-space-child',
		'taste' => ['modern'],
		'scene' => ['living-dining','terrace','carpet'],
		'area' => 'shibuya',
		'price' => '0-to-18000',
	],
	'studio-owl' => [
		'group' => 'management-space-child',
		'taste' => ['natural','modern','european'],
		'scene' => ['living-dining','kitchen','washroom','bedroom','terrace'],
		'area' => 'shibuya',
		'price' => '21000-to-24000',
	],
	'space-hf' => [
		'group' => 'management-space-child',
		'taste' => ['antique'],
		'scene' => ['garden','living-dining'],
		'area' => 'shibuya',
		'price' => '24000-over',
	],
	'sono' => [
		'group' => 'management-space-sono-child',
		'taste' => ['natural','modern'],
		'scene' => ['garden','living-dining','kitchen','washroom'],
		'area' => 'shibuya',
		'price' => '　',
	],
	'sanaizaka' => [
		'group' => 'sanaizaka-503',
		'taste' => ['natural','modern'],
		'scene' => ['garden','living-dining','kitchen','entrance','building'],
		'area' => 'shibuya',
		'price' => '21000-to-24000',
	],
];
