<?php
$studio_pos_meta_array = [
	'uehara-1f' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-uehara-1f'),
		'studio_post_order' => 1,
		'studio_operating_hour' => '8:30～19:00',
		'studio_minimum_usage_hour' => '5h',
		'studio_still_shooting_price_weekday' => '26400',
		'studio_still_shooting_price_holidays' => '31680',
		'studio_movie_shooting_ptice_weekday' => '',
		'studio_movie_shooting_ptice_holidays' => '',
	],
	'uehara-2f' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-uehara-2f'),
		'studio_post_order' => 2,
		'studio_operating_hour' => '8:30～19:00',
		'studio_minimum_usage_hour' => '5h',
		'studio_still_shooting_price_weekday' => '20900',
		'studio_still_shooting_price_holidays' => '25080',
		'studio_movie_shooting_ptice_weekday' => '',
		'studio_movie_shooting_ptice_holidays' => '',
	],
	'hiroo-1f' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-hiroo-1f'),
		'studio_post_order' => 3,
		'studio_operating_hour' => '8:30～19:00',
		'studio_minimum_usage_hour' => '4h',
		'studio_still_shooting_price_weekday' => '27500',
		'studio_still_shooting_price_holidays' => '33000',
		'studio_movie_shooting_ptice_weekday' => '',
		'studio_movie_shooting_ptice_holidays' => '',
	],
	'hiroo-2f' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-hiroo-2f'),
		'studio_post_order' => 4,
		'studio_operating_hour' => '8:30～19:00',
		'studio_minimum_usage_hour' => '4h',
		'studio_still_shooting_price_weekday' => '20900',
		'studio_still_shooting_price_holidays' => '25080',
		'studio_movie_shooting_ptice_weekday' => '',
		'studio_movie_shooting_ptice_holidays' => '',
	],
	'natural' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-natural'),
		'studio_post_order' => 5,
		'studio_operating_hour' => '8:00～20:00',
		'studio_minimum_usage_hour' => '4h',
		'studio_still_shooting_price_weekday' => '22000',
		'studio_still_shooting_price_holidays' => '26400',
		'studio_movie_shooting_ptice_weekday' => '33000',
		'studio_movie_shooting_ptice_holidays' => '39600',
	],
	'country' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-country'),
		'studio_post_order' => 6,
		'studio_operating_hour' => '8:00～20:00',
		'studio_minimum_usage_hour' => '4h',
		'studio_still_shooting_price_weekday' => '13200',
		'studio_still_shooting_price_holidays' => '15840',
		'studio_movie_shooting_ptice_weekday' => '18700',
		'studio_movie_shooting_ptice_holidays' => '22440',
	],
	'shabby-chic' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-shabby-chic'),
		'studio_post_order' => 7,
		'studio_operating_hour' => '8:00～20:00',
		'studio_minimum_usage_hour' => '4h',
		'studio_still_shooting_price_weekday' => '19800',
		'studio_still_shooting_price_holidays' => '23760',
		'studio_movie_shooting_ptice_weekday' => '29700',
		'studio_movie_shooting_ptice_holidays' => '35640',
	],
	'resort' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-resort'),
		'studio_post_order' => 8,
		'studio_operating_hour' => '8:00～20:00',
		'studio_minimum_usage_hour' => '4h',
		'studio_still_shooting_price_weekday' => '19800',
		'studio_still_shooting_price_holidays' => '23760',
		'studio_movie_shooting_ptice_weekday' => '29700',
		'studio_movie_shooting_ptice_holidays' => '35640',
	],
	'paruru' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-paruru'),
		'studio_post_order' => 9,
		'studio_operating_hour' => '8:00～20:00',
		'studio_minimum_usage_hour' => '4h',
		'studio_still_shooting_price_weekday' => '22000',
		'studio_still_shooting_price_holidays' => '26400',
		'studio_movie_shooting_ptice_weekday' => '33000',
		'studio_movie_shooting_ptice_holidays' => '39600',
	],
	'atlier-todoroki' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-atlier-todoroki'),
		'studio_post_order' => 10,
		'studio_operating_hour' => '',
		'studio_minimum_usage_hour' => '',
		'studio_still_shooting_price_weekday' => '',
		'studio_still_shooting_price_holidays' => '',
		'studio_movie_shooting_ptice_weekday' => '',
		'studio_movie_shooting_ptice_holidays' => '',
	],
	'studio-owl' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-studio-owl'),
		'studio_post_order' => 11,
		'studio_operating_hour' => '',
		'studio_minimum_usage_hour' => '',
		'studio_still_shooting_price_weekday' => '',
		'studio_still_shooting_price_holidays' => '',
		'studio_movie_shooting_ptice_weekday' => '',
		'studio_movie_shooting_ptice_holidays' => '',
	],
	'basil' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-basil'),
		'studio_post_order' => 12,
		'studio_operating_hour' => '月/金 7:00～20:00 <br>土日祝 8:00～20:00',
		'studio_minimum_usage_hour' => '5h',
		'studio_still_shooting_price_weekday' => '24200',
		'studio_still_shooting_price_holidays' => '29040',
		'studio_movie_shooting_ptice_weekday' => '33000',
		'studio_movie_shooting_ptice_holidays' => '39600',
	],
	'mint' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-mint'),
		'studio_post_order' => 13,
		'studio_operating_hour' => '月/金 7:00～20:00 <br>土日祝 8:00～20:00',
		'studio_minimum_usage_hour' => '5h',
		'studio_still_shooting_price_weekday' => '26400',
		'studio_still_shooting_price_holidays' => '31680',
		'studio_movie_shooting_ptice_weekday' => '35200',
		'studio_movie_shooting_ptice_holidays' => '42240',
	],
	'sage' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-sage'),
		'studio_post_order' => 14,
		'studio_operating_hour' => '月/金 7:00～20:00 <br>土日祝 8:00～20:00',
		'studio_minimum_usage_hour' => '5h',
		'studio_still_shooting_price_weekday' => '26400',
		'studio_still_shooting_price_holidays' => '31680',
		'studio_movie_shooting_ptice_weekday' => '35200',
		'studio_movie_shooting_ptice_holidays' => '42240',

	],
	'maison-de-bran' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-maison-de-bran'),
		'studio_post_order' => 15,
		'studio_operating_hour' => '8:00～20:00',
		'studio_minimum_usage_hour' => '4h',
		'studio_still_shooting_price_weekday' => '17600',
		'studio_still_shooting_price_holidays' => '21120',
		'studio_movie_shooting_ptice_weekday' => '27500',
		'studio_movie_shooting_ptice_holidays' => '33000',
	],
	'anchor' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-anchor'),
		'studio_post_order' => 16,
		'studio_operating_hour' => '月/金 7:00～20:00 <br>土日祝 8:00～20:00',
		'studio_minimum_usage_hour' => '5h',
		'studio_still_shooting_price_weekday' => '24200',
		'studio_still_shooting_price_holidays' => '29040',
		'studio_movie_shooting_ptice_weekday' => '35200',
		'studio_movie_shooting_ptice_holidays' => '42240',

	],
	'compass' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-compass'),
		'studio_post_order' => 17,
		'studio_operating_hour' => '月/金 7:00～20:00 <br>土日祝 8:00～20:00',
		'studio_minimum_usage_hour' => '5h',
		'studio_still_shooting_price_weekday' => '24200',
		'studio_still_shooting_price_holidays' => '29040',
		'studio_movie_shooting_ptice_weekday' => '35200',
		'studio_movie_shooting_ptice_holidays' => '42240',

	],
	'sailor' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-sailor'),
		'studio_post_order' => 18,
		'studio_operating_hour' => '月/金 7:00～20:00 <br>土日祝 8:00～20:00',
		'studio_minimum_usage_hour' => '5h',
		'studio_still_shooting_price_weekday' => '24200',
		'studio_still_shooting_price_holidays' => '29040',
		'studio_movie_shooting_ptice_weekday' => '35200',
		'studio_movie_shooting_ptice_holidays' => '42240',

	],
	'sanaizaka' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-sanaizaka'),
		'studio_post_order' => 19,
		'studio_operating_hour' => '',
		'studio_minimum_usage_hour' => '',
		'studio_still_shooting_price_weekday' => '',
		'studio_still_shooting_price_holidays' => '',
		'studio_movie_shooting_ptice_weekday' => '',
		'studio_movie_shooting_ptice_holidays' => '',
	],
	'a-studio' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-a-studio'),
		'studio_post_order' => 20,
		'studio_operating_hour' => '月/金 8:00～18:00 <br>土日祝 8:00～18:00',
		'studio_minimum_usage_hour' => '4h',
		'studio_still_shooting_price_weekday' => '22000',
		'studio_still_shooting_price_holidays' => '26400',
		'studio_movie_shooting_ptice_weekday' => '29700',
		'studio_movie_shooting_ptice_holidays' => '35640',

	],
	'b-studio' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-b-studio'),
		'studio_post_order' => 21,
		'studio_operating_hour' => '月/金 8:00～18:00 <br>土日祝 8:00～18:00',
		'studio_minimum_usage_hour' => '4h',
		'studio_still_shooting_price_weekday' => '17600',
		'studio_still_shooting_price_holidays' => '21120',
		'studio_movie_shooting_ptice_weekday' => '23100',
		'studio_movie_shooting_ptice_holidays' => '27720',

	],
	'c-studio' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-c-studio'),
		'studio_post_order' => 22,
		'studio_operating_hour' => '月/金 8:00～18:00 <br>土日祝 8:00～18:00',
		'studio_minimum_usage_hour' => '4h',
		'studio_still_shooting_price_weekday' => '19800',
		'studio_still_shooting_price_holidays' => '23760',
		'studio_movie_shooting_ptice_weekday' => '26400',
		'studio_movie_shooting_ptice_holidays' => '31680',

	],
	'lemon' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-lemon'),
		'studio_post_order' => 23,
		'studio_operating_hour' => '月/金 7:00～20:00 <br>土日祝 8:00～20:00',
		'studio_minimum_usage_hour' => '5h',
		'studio_still_shooting_price_weekday' => '27500',
		'studio_still_shooting_price_holidays' => '33000',
		'studio_movie_shooting_ptice_weekday' => '38500',
		'studio_movie_shooting_ptice_holidays' => '46200',
	],
	'lime' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-lime'),
		'studio_post_order' => 24,
		'studio_operating_hour' => '月/金 7:00～20:00 <br>土日祝 8:00～20:00',
		'studio_minimum_usage_hour' => '5h',
		'studio_still_shooting_price_weekday' => '27500',
		'studio_still_shooting_price_holidays' => '33000',
		'studio_movie_shooting_ptice_weekday' => '38500',
		'studio_movie_shooting_ptice_holidays' => '46200',

	],
	'flat' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-flat'),
		'studio_post_order' => 25,
		'studio_operating_hour' => '月/金 7:00～20:00 <br>土日祝 8:00～20:00',
		'studio_minimum_usage_hour' => '5h',
		'studio_still_shooting_price_weekday' => '25300',
		'studio_still_shooting_price_holidays' => '30360',
		'studio_movie_shooting_ptice_weekday' => '35200',
		'studio_movie_shooting_ptice_holidays' => '42240',
	],
	'1-studio' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-1-studio'),
		'studio_post_order' => 26,
		'studio_operating_hour' => '月/金 7:00～20:00 <br>土日祝 8:00～20:00',
		'studio_minimum_usage_hour' => '4h',
		'studio_still_shooting_price_weekday' => '16500',
		'studio_still_shooting_price_holidays' => '19800',
		'studio_movie_shooting_ptice_weekday' => '25300',
		'studio_movie_shooting_ptice_holidays' => '30360',
	],
	'2-studio' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-2-studio'),
		'studio_post_order' => 27,
		'studio_operating_hour' => '月/金 7:00～20:00 <br>土日祝 8:00～20:00',
		'studio_minimum_usage_hour' => '4h',
		'studio_still_shooting_price_weekday' => '22000',
		'studio_still_shooting_price_holidays' => '26400',
		'studio_movie_shooting_ptice_weekday' => '30800',
		'studio_movie_shooting_ptice_holidays' => '36960',
	],
	'3-studio' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-3-studio'),
		'studio_post_order' => 28,
		'studio_operating_hour' => '月/金 7:00～20:00 <br>土日祝 8:00～20:00',
		'studio_minimum_usage_hour' => '4h',
		'studio_still_shooting_price_weekday' => '25300',
		'studio_still_shooting_price_holidays' => '30360',
		'studio_movie_shooting_ptice_weekday' => '35200',
		'studio_movie_shooting_ptice_holidays' => '42240',
	],
	'4-studio' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-4-studio'),
		'studio_post_order' => 29,
		'studio_operating_hour' => '月/金 7:00～20:00 <br>土日祝 8:00～20:00',
		'studio_minimum_usage_hour' => '4h',
		'studio_still_shooting_price_weekday' => '',
		'studio_still_shooting_price_holidays' => '',
		'studio_movie_shooting_ptice_weekday' => '',
		'studio_movie_shooting_ptice_holidays' => '',
	],
	'sono' => [
		'_thumbnail_id' => vanilla_get_attachment_post_id('thumbnail-sono'),
		'studio_post_order' => 30,
		'studio_operating_hour' => '',
		'studio_minimum_usage_hour' => '',
		'studio_still_shooting_price_weekday' => '',
		'studio_still_shooting_price_holidays' => '',
		'studio_movie_shooting_ptice_weekday' => '',
		'studio_movie_shooting_ptice_holidays' => '',
	],
];
